
project_id = "nidnzvlojznpcoxnwefx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.razorpay-order]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false
