// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoqpdvcbxumihhvdwieh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcXBkdmNieHVtaWhodmR3aWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTM3MzUsImV4cCI6MjA1ODg4OTczNX0.Wa_KhKVGgv_STknf8netgghaku6LeuNh2EoHEMz74K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);