// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nidnzvlojznpcoxnwefx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZG56dmxvanpucGNveG53ZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjYxNjAsImV4cCI6MjA2NDM0MjE2MH0.ESMNy_ZvzypB6DDG7sOopNiqdvp22YL5TcJhaTGgIBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);